fix: mis-worded error messages

diff --git a/bin/git-push-all b/bin/git-push-all
--- a/bin/git-push-all
+++ b/bin/git-push-all
@@ -14,7 +14,7 @@ set -eu
 
 main() {
   if [ $# -gt 0 ]; then
-    echo "error: git-whoami does not accept any arguments" >&2
+    echo "error: git-push-all does not accept any arguments" >&2
     return 1
   fi
 
diff --git a/bin/git-wip b/bin/git-wip
--- a/bin/git-wip
+++ b/bin/git-wip
@@ -17,7 +17,7 @@ set -eu
 
 main() {
   if [ $# -gt 0 ]; then
-    echo "error: git-whoami does not accept any arguments" >&2
+    echo "error: git-wip does not accept any arguments" >&2
     return 1
   fi
 
