dev: add basic parameter validation

diff --git a/bin/git-cm b/bin/git-cm
--- a/bin/git-cm
+++ b/bin/git-cm
@@ -14,7 +14,12 @@ set -eu
 #
 
 main() {
+  if [ $# -gt 0 ]; then
+    echo "error: git-whoami does not accept any arguments" >&2
+    return 1
+  fi
+
   # ...
 }
 
-main
+main "$@"
diff --git a/bin/git-default b/bin/git-default
--- a/bin/git-default
+++ b/bin/git-default
@@ -12,7 +12,12 @@ set -eu
 #
 
 main() {
+  if [ $# -gt 0 ]; then
+    echo "error: git-whoami does not accept any arguments" >&2
+    return 1
+  fi
+
   # git rev-parse --abbrev-ref --symbolic-full-name origin/HEAD | sed 's@^origin/@@'
 }
 
-main
+main "$@"
diff --git a/bin/git-fell b/bin/git-fell
--- a/bin/git-fell
+++ b/bin/git-fell
@@ -12,7 +12,12 @@ set -eu
 #
 
 main() {
+  if [ $# -gt 0 ]; then
+    echo "error: git-whoami does not accept any arguments" >&2
+    return 1
+  fi
+
   # git branch --merged "${1:-$(git default)}" | grep -vE '^\*|master|main|dev' | xargs -r git branch -d
 }
 
-main
+main "$@"
diff --git a/bin/git-ff b/bin/git-ff
--- a/bin/git-ff
+++ b/bin/git-ff
@@ -11,10 +11,15 @@ set -eu
 #
 
 main() {
+  if [ $# -gt 0 ]; then
+    echo "error: git-whoami does not accept any arguments" >&2
+    return 1
+  fi
+
   # branch=${1:-main}
 
   # git checkout "$branch"
   # git pull --ff-only
 }
 
-main
+main "$@"
diff --git a/bin/git-ignore b/bin/git-ignore
--- a/bin/git-ignore
+++ b/bin/git-ignore
@@ -11,8 +11,13 @@ set -eu
 #
 
 main() {
+  if [ $# -gt 0 ]; then
+    echo "error: git-whoami does not accept any arguments" >&2
+    return 1
+  fi
+
   # path=${1:-.}
   # git update-index --assume-unchanged "$path"
 }
 
-main
+main "$@"
diff --git a/bin/git-pick b/bin/git-pick
--- a/bin/git-pick
+++ b/bin/git-pick
@@ -11,6 +11,11 @@ set -eu
 #
 
 main() {
+  if [ $# -gt 0 ]; then
+    echo "error: git-whoami does not accept any arguments" >&2
+    return 1
+  fi
+
   # git cherry-pick "$@"
 }
 
